### ISSUE TITLE
The color 'Dark Red' (DRED) is not defined if vim is running in a GUI

### ISSUE THREAD

**Issue by boywhoroared** [viniciusban/vim-github-colorscheme#1]
Hi! When using gvim or macvim, the variable `s:DRED` (Dark Red) is not defined. It is only defined for the terminal versions. 

`s:DRED` is used for the Class and Function highlights.

**Comment by viniciusban** [comment]
Thank you. I'll fix this.

**Comment by viniciusban** [comment]
Done.
